spring:
  profiles:
    active: dev
  application:
    name: order-service

server:
  port: 8070
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api/v1


---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
      url: jdbc:postgresql://localhost:5432/orderServiceDB
      username: postgres
      password: postgres123
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect