services:
  mongoDB:
    image: mongo
    container_name: product-mongoDB
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example
        MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./data:/data/db